[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
rust-version = "1.74"
authors = ["DaniPopes <57450786+DaniPopes@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/danipopes/sulk"
keywords = ["ethereum", "solidity", "solc", "crypto", "compiler"]
categories = ["compilers", "cryptography", "cryptography::cryptocurrencies"]

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.lints.clippy]
dbg-macro = "warn"
use-self = "warn"
uninlined-format-args = "warn"
manual-string-new = "warn"

[workspace.lints.rust]
unreachable-pub = "warn"
unused-must-use = "deny"
unused-crate-dependencies = "warn"
rust-2018-idioms = "deny"

[workspace.lints.rustdoc]
all = "warn"

[workspace.dependencies]
sulk-ast = { version = "0.0.0", path = "crates/ast" }
sulk-data-structures = { version = "0.0.0", path = "crates/data-structures" }
sulk-interface = { version = "0.0.0", path = "crates/interface" }
sulk-macros = { version = "0.0.0", path = "crates/macros" }
sulk-parser = { version = "0.0.0", path = "crates/parser" }

alloy-primitives = "0.5"

# macros
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

# parallel
parking_lot = "0.12"
rayon = "1.8"

# testing
criterion = "0.5"
rand = "0.8"

# misc
ahash = "0.8"
bumpalo = "3.14"
expect-test = "1.4"
hex = { package = "const-hex", version = "1.10" }
index_vec = "0.1.3"
indexmap = "2.1"
rustc-hash = "1.1.0"
scoped-tls = "1.0.1"
semver = "1.0"
smallvec = "1"
unicode-ident = "1.0"
unicode-normalization = "0.1.22"
