[package]
name = "rsolc"
version = "0.1.0"
edition = "2021"
authors = ["DaniPopes <57450786+DaniPopes@users.noreply.github.com>"]
description = "Rust implementation of the Solidity language"
license = "MIT OR Apache-2.0"
repository = "https://github.com/danipopes/rsolc"
homepage = "https://github.com/danipopes/rsolc"
exclude = [".github/"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
