[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
version = "0.0.0"
edition = "2021"
rust-version = "1.74"
authors = ["DaniPopes <57450786+DaniPopes@users.noreply.github.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/danipopes/rsolc"
keywords = ["ethereum", "solidity", "solc", "crypto", "compiler"]
categories = ["compilers", "cryptography", "cryptography::cryptocurrencies"]

[workspace.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[workspace.dependencies]
rsolc-ast = { version = "0.0.0", path = "crates/ast" }
rsolc-data-structures = { version = "0.0.0", path = "crates/data-structures" }
rsolc-macros = { version = "0.0.0", path = "crates/macros" }
rsolc-parser = { version = "0.0.0", path = "crates/parser" }
rsolc-span = { version = "0.0.0", path = "crates/span" }

# macros
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

# parallel
rayon = "1.8"
parking_lot = "0.12"

# misc
bumpalo = "3.14"
expect-test = "1.4"
indexmap = "2.1"
rustc-hash = "1.1.0"
scoped-tls = "1.0.1"
smallvec = "1"
unicode-ident = "1.0"
unicode-normalization = "0.1.22"
index_vec = "0.1.3"
