[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.65"
license = "MIT OR Apache-2.0"
repository = "https://github.com/danipopes/rsolc"
keywords = ["ethereum", "solidity", "solc", "crypto"]
categories = ["cryptography", "cryptography::cryptocurrencies"]
