[package]
name = "sulk"
description = "Solidity compiler"
homepage = "https://github.com/paradigmxyz/sulk/"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
sulk-data-structures.workspace = true
sulk-interface.workspace = true
sulk-parse.workspace = true
sulk-resolve.workspace = true

clap = { workspace = true, features = ["derive"] }
tracing-error.workspace = true
tracing-subscriber = { workspace = true, features = ["registry", "env-filter", "fmt"] }
# tracing.workspace = true

[dev-dependencies]
sulk-tester.workspace = true

[[test]]
name = "tests"
path = "./tests.rs"
