[alias]
xtask = "run --package xtask --bin xtask --"
tq = "xtask test"
qt = "tq"
ryul = "run --package sulk --bin sulk -- --language yul -Zparse-yul"
bless = "xtask test --bless"
uitest = "xtask test ui"
uibless = "xtask test ui --bless"
