[package]
name = "rsolc-data-structures"
description = "RSolc common data structures"
homepage = "https://github.com/danipopes/rsolc/blob/master/crates/data-structures"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
smallvec = { workspace = true, features = ["union"] }
rustc-hash.workspace = true
indexmap.workspace = true
index_vec.workspace = true

[features]
nightly = ["smallvec/specialization", "smallvec/may_dangle"]
