[package]
name = "rsolc-data-structures"
description = "RSolc common data structures"
homepage = "https://github.com/danipopes/rsolc/blob/master/crates/data-structures"

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
ahash.workspace = true
smallvec = { workspace = true, features = ["union"] }
rustc-hash.workspace = true
indexmap.workspace = true
index_vec.workspace = true

# parallel
rayon = { workspace = true, optional = true }
parking_lot = { workspace = true, optional = true }

[features]
nightly = ["smallvec/specialization", "smallvec/may_dangle", "parking_lot?/nightly"]
parallel = ["dep:rayon", "dep:parking_lot"]
