[package]
name = "sulk-bench"
description = "Simple benchmarks across different Solidity parser implementations"
homepage = "https://github.com/paradigmxyz/sulk/tree/main/benches"
publish = false

version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
criterion = "0.5"

sulk-parse.workspace = true

solang-parser = "=0.3.3"

slang_solidity = "=0.14.0"
semver.workspace = true

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
